{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cloudflare-api-key-secret",
    "namespace": "cert-manager"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cloudflare-api-key-secret",
        "namespace": "cert-manager"
      }
    },
    "encryptedData": {
      "api-key": "AgB+14sPXkCn89ZD9YbwGf+MmH/UnZ8GEXnGD4e85qiKTjr/sFubNfKOfVOleHgYK/AAsXbnsLB5GUACG5eJdGq/7UcBFZLKi2CLkSKyzTyOxapx3w6No5jHhJq+MpkSxhQxuamL9buoty8SPRolERxaG79AReWCMFSJUx90fpNPloTxp5cVmULmFyLv8dyYIMWzdLzKr7bxxl46yFzXbz9gOoFj7Xx3YWJGH4Z1GLEeC6KD/SoGD5ogwaCtUjk8Y6w7bFo/coI025AEb2446ZM1JFWe31ikr0T0T02TfXp07U9COA/cw2WnIS2KOyWPqnW88HpQL1U3FynEab7KDfkrQLWTmTx7fDdSz9RLc9KbcyekeZFJZqW1QeVRWqZP2FxitevO1pXc7+4xetiPqxmWjjo4XXBEWbKbWe0mziahXLlaVsA0qfcIL1K4PTjb5Ss5bPcxiA+T9p+xsPXu0dpIxMmltgEWHnOgMQrLoZ3qF+LMtV6YxAlNHCrV/njOTvlTjyhtZN+WoiCMEdVcchcCAcpBKSzjMTGJBtXC5mDm3P0T05tAzbMynyx+puE9zWhCAqnXZH7bXd2GTBeYufEOtVVyciY3zcGm0bBbrl7mLF7RguRMdrMGNCby0nweoP8LwdqdRbtkpD8C6HCeUt9exwAJL+r9+R4dQAFTViOwbDfDmy9cuGvdaK2y+bIBJrC9YLIroBzfB/BTlqO+8YrP8u2cNH2TVqmTuDtFhFEi9eSde+KX"
    }
  }
}
