{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "pihole-password",
    "namespace": "external-dns"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "pihole-password",
        "namespace": "external-dns"
      }
    },
    "encryptedData": {
      "EXTERNAL_DNS_PIHOLE_PASSWORD": "AgAeoRK5ewYXKOGjci1xQeETlnUC3Qyn3jABo6r+04FDQQdz1iVCG7vVl+PX7XiUD9JcrfkUwMtoYkX3RLDLdgHgH31i5W1p5nOndQA2nfhmiZNzYYO0w8PdBaBWbGZZDP7CuLwSw1BMV/wUMD5kwOv22Zr7W2tccvpucM5QfQJ23cmqhVTrOoAfC/6+ka+FxVgaEOYK0YLEk91MeH6OA5afkGuTrW7d+dkUiZory7zOq769iuD7vzFQ2N6HplDa8BSsssrB6zduPtpG1tWxZALgs8bQhFAtO+G0lerUVVU4/NYdPj2a4LQ1BuQ+JzjfMPL6qpuw0hulU0mu+hM2DHBGHPHLf3w+briYLkW2emaht7C1dd7sKw8SMq6XdgrdwCH0vLHjC+j9lriimL/BWKT/x3zmmv5L7EQgmE0rwPsupk2VLsrk7rJ3KGsr4oyJTuthk50FGR8C0K9gVd+ZaZ0amtExmZQYXVbNjhwhHAbZQPybmTlUAzf0ey8K3zOP7zRWGLffZO1KE0vVOglnfjQHQivAeUMbiPYzDCm5TtTGjgqHnhkmcrfY+oiK3ve+YvtXQkE4LZIHkznvf+9kQWDvgCRTzFIezgWW7/b+btA3Ahu5+F7ByHXwFrux/IQAeZ9DdACyY0xphrSthdIeL/qCaAEfcJ6lgqJuS8jutsSkh5TcNHU3tsXt2Y+T5huaFaMV2UEdQ05fVep3EKuD1Q=="
    }
  }
}
