apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infastructure
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://git.greyroom.net/mattia/gitops.git
      revision: main
      directories:
      - path: infrastructure/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: "default"
      source:
        repoURL: https://git.greyroom.net/mattia/gitops.git
        targetRevision: main
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
